try{x=1}
catch(ex){alert(ex)}
finally{alert("done")}
